#!/usr/bin/env python3

import subprocess
import sys

def failed(code):
    return code != 0

def command():
    try:
        return sys.argv[1]
    except IndexError:
        return ''

def run(*cmd_list):
    completed = subprocess.run(cmd_list, text=True, capture_output=True)
    output = completed.stdout
    err_output = completed.stderr
    exit_code = completed.returncode
    if failed(exit_code):
        return err_output, exit_code
    return output, exit_code

def git_commit(message=''):
    return run('git', 'commit', '-m', message, "--amend")

def print_response(cmd):
    if cmd == 'all':
        print("Locked all files")
    else:
        print("Locked staged files")

if __name__ == '__main__':
    cmd = command()

    if cmd == 'all':
        output, code = run('git', 'add', '-A')
        if failed(code):
            print("Failed to add all files:", output)
            sys.exit(1)

    output, code = git_commit("vault")
    if failed(code):
        print("Failed to commit:", output)
        sys.exit(1)

    print_response(cmd)
